---
title: ''
author: "Hope Hahn, Ben Versteeg"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Combined metric

In our combined metric, we will be combining:

* relative error in annual maximum flow estimate
* relative error in monthly flow during high flow period
* correlation between observed and modelled annual maximum flow
* correlation between observed and modelled flow during the high flow period

```{r}
source("hope_ben_compute_highflowmetrics_all.R")
```

## Calibration

```{r}
# multiple results - lets say we've run the model for multiple years, each column
# is streamflow for a different parameter set
msage = read.table("sagerm.txt", header=T)

# use the date from the previous dataset
msage$date = sager$date
head(msage)
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy

msagel = msage %>%
  pivot_longer(cols=!c(date, month, year, day,wy), 
               names_to="run", 
               values_to="flow")

# create a subset of data for calibration
msage_calibration <- msage %>% 
  filter(wy == 1966)

msage1_calibration <- msagel %>% 
  filter(wy == 1966)

sager_calibration <- sager %>% 
  filter(wy == 1966)

# get metrics for  
res_calibration = msage_calibration %>% 
  select(-date, -month, -day, -year, -wy ) %>% 
  # this line applies our function to the dataset
  map_df(compute_highflowmetrics_all, 
         o=sager_calibration$obs, 
         month=msage_calibration$month, 
         day=msage_calibration$day, 
         year=msage_calibration$year, 
         wy=msage_calibration$wy)

# plot the thing
resl_calibration = res_calibration %>% 
  pivot_longer(cols=everything(), 
               names_to="metric",
               values_to="value")

ggplot(resl_calibration, aes(metric, value))+
  geom_boxplot()+
  facet_wrap(~metric, scales="free")

# try this
# assign an identifier to each row, use the same identify for columns of original streamflow data
# we can then use that to pick data
res_calibration$run = seq(from=1,to=nrow(res_calibration))
head(msage_calibration)
colnames(msage_calibration)=c(res_calibration$run, "date","month","year","day","wy")

# best one
best_calibration = res_calibration[which.max(res_calibration$combined),]
msagel_calibration  =  msage_calibration %>%
  pivot_longer(cols=!c(date, month, year, day,wy), 
                   names_to="run", 
                   values_to="flow")

ggplot(subset(msagel_calibration, run == best$run), aes(date, flow)) + geom_line()

```

